Coaching\UserBundle\Entity\Coaching:
  exclusion_policy: ALL
  xml_root_name: coaching
  properties:
    id:
      expose: true
    teacher:
      expose: true
    student:
      expose: true
    startDate:
      serialized_name: start_date
      expose: true
    endDate:
      serialized_name: end_date
      expose: true
    status:
      expose: true