Coaching\UserBundle\Entity\coaching:
  exclusion_policy: ALL
  xml_root_name: coaching
  properties:
    id:
      expose: true
    teacher:
      expose: true
    student:
      expose: true
    startDate:
      expose: true
    endDate:
      expose: true
    status:
      expose: true
