Comment:
    type: entity
    table: comment
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        authorId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: author_id
        receptorId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: receptor_id
        coachingId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: coaching_id
        grade:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        content:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
