Message:
    type: entity
    table: message
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        authorId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: author_id
        threadId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            column: thread_id
        content:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
