parameters:
#    coaching_user.example.class: Coaching\UserBundle\Example

services:
#    coaching_user.example:
#        class: %coaching_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
